"""Add Follow and Badge models

Revision ID: 026823b752da
Revises: fa0368413663
Create Date: 2026-05-14 16:34:36.738977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026823b752da'
down_revision = 'fa0368413663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_type', sa.Enum('FIRST_BITE', 'SUBURB_SCOUT', 'GLOBE_TROTTER', 'ON_FIRE', 'PEN_AND_FORK', 'RUTHLESSLY_ACCURATE', name='badgetype'), nullable=False),
    sa.Column('awarded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'badge_type', name='uq_user_badge')
    )
    op.create_table('follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'followed_id', name='uq_follow')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    op.drop_table('badges')
    # ### end Alembic commands ###
