"""drop profile_is_public column

Revision ID: f9e95ef52ebf
Revises: 026823b752da
Create Date: 2026-05-15 23:26:24.867494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e95ef52ebf'
down_revision = '026823b752da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_is_public')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_is_public', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
